In [1]:
import requests
import pandas as pd
from pprint import pprint


base_url = "https://kiwicom-prod.apigee.net/v2/search?"
apikey= "apikey=APlFNwzVYPN7Ies4YQzavAnYfqKvDLib"
from_city = "&fly_from="
to_city = "&fly_to="
start = "&date_from="
origin = "ORD"
dest_cities = ["LGA","SFO","JFK","ATL","EWR","LAX"]
date = "&date_from="
date_to = "&date_to="
curr = "&curr="
currency = "USD"
stops = "&max_stopovers="
num_stops = 0
query_list = []
response = []
prices = []
airlines = []
airport = []
destination_city = []
fare_family = []
fare_class = []
cityFrom = []
local_departure = []
local_arrival = []
distance = []
bags_price = []
flight_no = []
d=1
m=1

In [2]:
 for r in range(len(dest_cities)):
    
    for m in range(6):
        if m == 0:
            for d in range(28):
                start = (f"{d+1}%2F{m+2}%2F2019")
                end = (f"{d+1}%2F{m+2}%2F2019")

                query_url = (f"{base_url}{apikey}{from_city}{origin}{to_city}{dest_cities[r]}{date}{start}{date_to}{end}{curr}{currency}{stops}{num_stops}")
                responses = (requests.get(query_url).json())
                query_list.append(query_url)

                for x in range(len(responses['data'])):   
                    prices.append(responses['data'][x]['price'])
                    airlines.append(responses['data'][x]['airlines'])  
                    airport.append(responses['data'][x]['route'][0]['flyTo'])
                    destination_city.append(responses['data'][x]['route'][0]['cityTo'])
                    fare_family.append(responses['data'][x]['route'][0]['fare_family'])
                    fare_class.append(responses['data'][x]['route'][0]['fare_classes'])
                    cityFrom.append(responses['data'][x]['route'][0]['cityFrom'])
                    local_departure.append(responses['data'][x]['route'][0]['local_departure'])
                    local_arrival.append(responses['data'][x]['route'][0]['local_arrival'])
                    distance.append(responses['data'][x]['distance'])
                    bags_price.append(responses['data'][x]['bags_price']['1'])
                    flight_no.append(responses['data'][x]['route'][0]['flight_no'])
        
        elif m == 2 or m==4:
            for d in range(30):
                start = (f"{d+1}%2F{m+2}%2F2019")
                end = (f"{d+1}%2F{m+2}%2F2019")

                query_url = (f"{base_url}{apikey}{from_city}{origin}{to_city}{dest_cities[r]}{date}{start}{date_to}{end}{curr}{currency}{stops}{num_stops}")
                responses = (requests.get(query_url).json())
                query_list.append(query_url)

                for x in range(len(responses['data'])):   
                    prices.append(responses['data'][x]['price'])
                    airlines.append(responses['data'][x]['airlines'])  
                    airport.append(responses['data'][x]['route'][0]['flyTo'])
                    destination_city.append(responses['data'][x]['route'][0]['cityTo'])
                    fare_family.append(responses['data'][x]['route'][0]['fare_family'])
                    fare_class.append(responses['data'][x]['route'][0]['fare_classes'])
                    cityFrom.append(responses['data'][x]['route'][0]['cityFrom'])
                    local_departure.append(responses['data'][x]['route'][0]['local_departure'])
                    local_arrival.append(responses['data'][x]['route'][0]['local_arrival'])
                    distance.append(responses['data'][x]['distance'])
                    bags_price.append(responses['data'][x]['bags_price']['1'])
                    flight_no.append(responses['data'][x]['route'][0]['flight_no'])
                    
        elif m == 1 or m==3 or m==5:
            for d in range(31):
                start = (f"{d+1}%2F{m+2}%2F2019")
                end = (f"{d+1}%2F{m+2}%2F2019")

                query_url = (f"{base_url}{apikey}{from_city}{origin}{to_city}{dest_cities[r]}{date}{start}{date_to}{end}{curr}{currency}{stops}{num_stops}")
                responses = (requests.get(query_url).json())
                query_list.append(query_url)

                for x in range(len(responses['data'])):   
                    prices.append(responses['data'][x]['price'])
                    airlines.append(responses['data'][x]['airlines'])  
                    airport.append(responses['data'][x]['route'][0]['flyTo'])
                    destination_city.append(responses['data'][x]['route'][0]['cityTo'])
                    fare_family.append(responses['data'][x]['route'][0]['fare_family'])
                    fare_class.append(responses['data'][x]['route'][0]['fare_classes'])
                    cityFrom.append(responses['data'][x]['route'][0]['cityFrom'])
                    local_departure.append(responses['data'][x]['route'][0]['local_departure'])
                    local_arrival.append(responses['data'][x]['route'][0]['local_arrival'])
                    distance.append(responses['data'][x]['distance'])
                    bags_price.append(responses['data'][x]['bags_price']['1'])
                    flight_no.append(responses['data'][x]['route'][0]['flight_no'])

    responses_dict = {'Price': prices,'Airline': airlines, 'flyTo': airport, 'cityTo': destination_city,
                             'fare_family': fare_family, 'fare_classes': fare_class,'cityFrom': cityFrom, 'local_departure': local_departure,
                             'local_arrival': local_arrival, 'distance': distance, 'bags_price': bags_price, 'flight_no': flight_no}
    responses_df = pd.DataFrame(responses_dict)
    response.append(responses_df)

In [3]:
response[1].head()

,Price,Airline,flyTo,cityTo,fare_family,fare_classes,cityFrom,local_departure,local_arrival,distance,bags_price,flight_no
0,54,[NK],LGA,New York,,U,Chicago,2019-02-01T05:51:00.000Z,2019-02-01T09:00:00.000Z,1178.35,37,224
1,54,[NK],LGA,New York,,U,Chicago,2019-02-01T17:43:00.000Z,2019-02-01T20:58:00.000Z,1178.35,37,630
2,56,[UA],LGA,New York,,N,Chicago,2019-02-01T07:30:00.000Z,2019-02-01T10:41:00.000Z,1178.35,22,427
3,56,[UA],LGA,New York,,N,Chicago,2019-02-01T21:05:00.000Z,2019-02-02T00:16:00.000Z,1178.35,22,2422
4,56,[UA],LGA,New York,,N,Chicago,2019-02-01T13:00:00.000Z,2019-02-01T16:11:00.000Z,1178.35,22,682

In [4]:
len(response)

6

In [5]:
response[0].to_csv('LGA.csv')
response[1].to_csv('SFO.csv')
response[2].to_csv('JFK.csv')
response[3].to_csv('ATL.csv')
response[4].to_csv('EWR.csv')
response[5].to_csv('LAX.csv')

In [ ]:
#this is the part we need to work on

merged_dfA = response[1].merge(response[2], how = 'outer', on = 'flight_no')
merged_dfB = response[3].merge(response[4], how = 'outer', on = 'flight_no')
merged_dfC = response[0].merge(response[5], how = 'outer', on = 'flight_no')
merged_dfD = merged_dfA.merge(merged_dfB, how = 'outer', on = 'flight_no')
merged_df = merged_dfC.merge(merged_dfD, how = 'outer', on = 'flight_no')
print(merged_df)

In [ ]:
merged_df.dropna()